services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Letkode\HelpersBundle\:
        resource: '../src/'
        exclude:
            - '../src/LetkodeHelpersBundle.php'
            - '../src/Contract/'
            - '../src/Exception/'
